server:
  port: 3000
#日志处理
logging:
  level:
    com.zdb.demo: DEBUG


#MyBatis配置
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manage?characterEncoding=utf-8&amp&serverTimezone=UTC&amp&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

#PagerHelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql

eureka:
  client:
    register-with-eureka: false #禁止自己当做服务注册
    fetch-registry: false       #屏蔽注册信息
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB