server:
  port: 3000
#日志处理
logging:
  level:
    com.zdb.demo: DEBUG

#MyBatis配置
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://120.55.48.156:3306/shop?characterEncoding=utf-8&amp&serverTimezone=UTC&amp&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: shop
    password: ZrafHSdTRLGzKMxT

#PagerHelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params:
    count: countSql