package com.zdb.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CardExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table card
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     *  构造查询条件,card
     */
    public CardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,card
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,card
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,card
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,card
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,card
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,card
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,card
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,card
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,card
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,card
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,card
     *
     * @param limitStart
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * ,card
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * ,card
     *
     * @param limitEnd
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * ,card
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * 
     * GeneratedCriteria
     * 数据库表：card
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNull() {
            addCriterion("keywords is null");
            return (Criteria) this;
        }

        public Criteria andKeywordsIsNotNull() {
            addCriterion("keywords is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordsEqualTo(String value) {
            addCriterion("keywords =", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotEqualTo(String value) {
            addCriterion("keywords <>", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThan(String value) {
            addCriterion("keywords >", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("keywords >=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThan(String value) {
            addCriterion("keywords <", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLessThanOrEqualTo(String value) {
            addCriterion("keywords <=", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsLike(String value) {
            addCriterion("keywords like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotLike(String value) {
            addCriterion("keywords not like", value, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsIn(List<String> values) {
            addCriterion("keywords in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotIn(List<String> values) {
            addCriterion("keywords not in", values, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsBetween(String value1, String value2) {
            addCriterion("keywords between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andKeywordsNotBetween(String value1, String value2) {
            addCriterion("keywords not between", value1, value2, "keywords");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlIsNull() {
            addCriterion("backgroundUrl is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlIsNotNull() {
            addCriterion("backgroundUrl is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlEqualTo(String value) {
            addCriterion("backgroundUrl =", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlNotEqualTo(String value) {
            addCriterion("backgroundUrl <>", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlGreaterThan(String value) {
            addCriterion("backgroundUrl >", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlGreaterThanOrEqualTo(String value) {
            addCriterion("backgroundUrl >=", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlLessThan(String value) {
            addCriterion("backgroundUrl <", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlLessThanOrEqualTo(String value) {
            addCriterion("backgroundUrl <=", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlLike(String value) {
            addCriterion("backgroundUrl like", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlNotLike(String value) {
            addCriterion("backgroundUrl not like", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlIn(List<String> values) {
            addCriterion("backgroundUrl in", values, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlNotIn(List<String> values) {
            addCriterion("backgroundUrl not in", values, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlBetween(String value1, String value2) {
            addCriterion("backgroundUrl between", value1, value2, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlNotBetween(String value1, String value2) {
            addCriterion("backgroundUrl not between", value1, value2, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andIntroduceIsNull() {
            addCriterion("introduce is null");
            return (Criteria) this;
        }

        public Criteria andIntroduceIsNotNull() {
            addCriterion("introduce is not null");
            return (Criteria) this;
        }

        public Criteria andIntroduceEqualTo(String value) {
            addCriterion("introduce =", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotEqualTo(String value) {
            addCriterion("introduce <>", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceGreaterThan(String value) {
            addCriterion("introduce >", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceGreaterThanOrEqualTo(String value) {
            addCriterion("introduce >=", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLessThan(String value) {
            addCriterion("introduce <", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLessThanOrEqualTo(String value) {
            addCriterion("introduce <=", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLike(String value) {
            addCriterion("introduce like", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotLike(String value) {
            addCriterion("introduce not like", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceIn(List<String> values) {
            addCriterion("introduce in", values, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotIn(List<String> values) {
            addCriterion("introduce not in", values, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceBetween(String value1, String value2) {
            addCriterion("introduce between", value1, value2, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotBetween(String value1, String value2) {
            addCriterion("introduce not between", value1, value2, "introduce");
            return (Criteria) this;
        }

        public Criteria andDakatimeIsNull() {
            addCriterion("dakatime is null");
            return (Criteria) this;
        }

        public Criteria andDakatimeIsNotNull() {
            addCriterion("dakatime is not null");
            return (Criteria) this;
        }

        public Criteria andDakatimeEqualTo(Date value) {
            addCriterion("dakatime =", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeNotEqualTo(Date value) {
            addCriterion("dakatime <>", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeGreaterThan(Date value) {
            addCriterion("dakatime >", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("dakatime >=", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeLessThan(Date value) {
            addCriterion("dakatime <", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeLessThanOrEqualTo(Date value) {
            addCriterion("dakatime <=", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeIn(List<Date> values) {
            addCriterion("dakatime in", values, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeNotIn(List<Date> values) {
            addCriterion("dakatime not in", values, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeBetween(Date value1, Date value2) {
            addCriterion("dakatime between", value1, value2, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeNotBetween(Date value1, Date value2) {
            addCriterion("dakatime not between", value1, value2, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakapoepleIsNull() {
            addCriterion("dakapoeple is null");
            return (Criteria) this;
        }

        public Criteria andDakapoepleIsNotNull() {
            addCriterion("dakapoeple is not null");
            return (Criteria) this;
        }

        public Criteria andDakapoepleEqualTo(String value) {
            addCriterion("dakapoeple =", value, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleNotEqualTo(String value) {
            addCriterion("dakapoeple <>", value, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleGreaterThan(String value) {
            addCriterion("dakapoeple >", value, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleGreaterThanOrEqualTo(String value) {
            addCriterion("dakapoeple >=", value, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleLessThan(String value) {
            addCriterion("dakapoeple <", value, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleLessThanOrEqualTo(String value) {
            addCriterion("dakapoeple <=", value, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleLike(String value) {
            addCriterion("dakapoeple like", value, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleNotLike(String value) {
            addCriterion("dakapoeple not like", value, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleIn(List<String> values) {
            addCriterion("dakapoeple in", values, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleNotIn(List<String> values) {
            addCriterion("dakapoeple not in", values, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleBetween(String value1, String value2) {
            addCriterion("dakapoeple between", value1, value2, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andDakapoepleNotBetween(String value1, String value2) {
            addCriterion("dakapoeple not between", value1, value2, "dakapoeple");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsIsNull() {
            addCriterion("FamousAllusions is null");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsIsNotNull() {
            addCriterion("FamousAllusions is not null");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsEqualTo(String value) {
            addCriterion("FamousAllusions =", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsNotEqualTo(String value) {
            addCriterion("FamousAllusions <>", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsGreaterThan(String value) {
            addCriterion("FamousAllusions >", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsGreaterThanOrEqualTo(String value) {
            addCriterion("FamousAllusions >=", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsLessThan(String value) {
            addCriterion("FamousAllusions <", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsLessThanOrEqualTo(String value) {
            addCriterion("FamousAllusions <=", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsLike(String value) {
            addCriterion("FamousAllusions like", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsNotLike(String value) {
            addCriterion("FamousAllusions not like", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsIn(List<String> values) {
            addCriterion("FamousAllusions in", values, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsNotIn(List<String> values) {
            addCriterion("FamousAllusions not in", values, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsBetween(String value1, String value2) {
            addCriterion("FamousAllusions between", value1, value2, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsNotBetween(String value1, String value2) {
            addCriterion("FamousAllusions not between", value1, value2, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andMoodIsNull() {
            addCriterion("mood is null");
            return (Criteria) this;
        }

        public Criteria andMoodIsNotNull() {
            addCriterion("mood is not null");
            return (Criteria) this;
        }

        public Criteria andMoodEqualTo(String value) {
            addCriterion("mood =", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotEqualTo(String value) {
            addCriterion("mood <>", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodGreaterThan(String value) {
            addCriterion("mood >", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodGreaterThanOrEqualTo(String value) {
            addCriterion("mood >=", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodLessThan(String value) {
            addCriterion("mood <", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodLessThanOrEqualTo(String value) {
            addCriterion("mood <=", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodLike(String value) {
            addCriterion("mood like", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotLike(String value) {
            addCriterion("mood not like", value, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodIn(List<String> values) {
            addCriterion("mood in", values, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotIn(List<String> values) {
            addCriterion("mood not in", values, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodBetween(String value1, String value2) {
            addCriterion("mood between", value1, value2, "mood");
            return (Criteria) this;
        }

        public Criteria andMoodNotBetween(String value1, String value2) {
            addCriterion("mood not between", value1, value2, "mood");
            return (Criteria) this;
        }

        public Criteria andWord1IsNull() {
            addCriterion("word1 is null");
            return (Criteria) this;
        }

        public Criteria andWord1IsNotNull() {
            addCriterion("word1 is not null");
            return (Criteria) this;
        }

        public Criteria andWord1EqualTo(String value) {
            addCriterion("word1 =", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1NotEqualTo(String value) {
            addCriterion("word1 <>", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1GreaterThan(String value) {
            addCriterion("word1 >", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1GreaterThanOrEqualTo(String value) {
            addCriterion("word1 >=", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1LessThan(String value) {
            addCriterion("word1 <", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1LessThanOrEqualTo(String value) {
            addCriterion("word1 <=", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1Like(String value) {
            addCriterion("word1 like", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1NotLike(String value) {
            addCriterion("word1 not like", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1In(List<String> values) {
            addCriterion("word1 in", values, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1NotIn(List<String> values) {
            addCriterion("word1 not in", values, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1Between(String value1, String value2) {
            addCriterion("word1 between", value1, value2, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1NotBetween(String value1, String value2) {
            addCriterion("word1 not between", value1, value2, "word1");
            return (Criteria) this;
        }

        public Criteria andImg1IsNull() {
            addCriterion("img1 is null");
            return (Criteria) this;
        }

        public Criteria andImg1IsNotNull() {
            addCriterion("img1 is not null");
            return (Criteria) this;
        }

        public Criteria andImg1EqualTo(String value) {
            addCriterion("img1 =", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1NotEqualTo(String value) {
            addCriterion("img1 <>", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1GreaterThan(String value) {
            addCriterion("img1 >", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1GreaterThanOrEqualTo(String value) {
            addCriterion("img1 >=", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1LessThan(String value) {
            addCriterion("img1 <", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1LessThanOrEqualTo(String value) {
            addCriterion("img1 <=", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1Like(String value) {
            addCriterion("img1 like", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1NotLike(String value) {
            addCriterion("img1 not like", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1In(List<String> values) {
            addCriterion("img1 in", values, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1NotIn(List<String> values) {
            addCriterion("img1 not in", values, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1Between(String value1, String value2) {
            addCriterion("img1 between", value1, value2, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1NotBetween(String value1, String value2) {
            addCriterion("img1 not between", value1, value2, "img1");
            return (Criteria) this;
        }

        public Criteria andWord2IsNull() {
            addCriterion("word2 is null");
            return (Criteria) this;
        }

        public Criteria andWord2IsNotNull() {
            addCriterion("word2 is not null");
            return (Criteria) this;
        }

        public Criteria andWord2EqualTo(String value) {
            addCriterion("word2 =", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2NotEqualTo(String value) {
            addCriterion("word2 <>", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2GreaterThan(String value) {
            addCriterion("word2 >", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2GreaterThanOrEqualTo(String value) {
            addCriterion("word2 >=", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2LessThan(String value) {
            addCriterion("word2 <", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2LessThanOrEqualTo(String value) {
            addCriterion("word2 <=", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2Like(String value) {
            addCriterion("word2 like", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2NotLike(String value) {
            addCriterion("word2 not like", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2In(List<String> values) {
            addCriterion("word2 in", values, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2NotIn(List<String> values) {
            addCriterion("word2 not in", values, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2Between(String value1, String value2) {
            addCriterion("word2 between", value1, value2, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2NotBetween(String value1, String value2) {
            addCriterion("word2 not between", value1, value2, "word2");
            return (Criteria) this;
        }

        public Criteria andImg2IsNull() {
            addCriterion("img2 is null");
            return (Criteria) this;
        }

        public Criteria andImg2IsNotNull() {
            addCriterion("img2 is not null");
            return (Criteria) this;
        }

        public Criteria andImg2EqualTo(String value) {
            addCriterion("img2 =", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2NotEqualTo(String value) {
            addCriterion("img2 <>", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2GreaterThan(String value) {
            addCriterion("img2 >", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2GreaterThanOrEqualTo(String value) {
            addCriterion("img2 >=", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2LessThan(String value) {
            addCriterion("img2 <", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2LessThanOrEqualTo(String value) {
            addCriterion("img2 <=", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2Like(String value) {
            addCriterion("img2 like", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2NotLike(String value) {
            addCriterion("img2 not like", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2In(List<String> values) {
            addCriterion("img2 in", values, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2NotIn(List<String> values) {
            addCriterion("img2 not in", values, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2Between(String value1, String value2) {
            addCriterion("img2 between", value1, value2, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2NotBetween(String value1, String value2) {
            addCriterion("img2 not between", value1, value2, "img2");
            return (Criteria) this;
        }

        public Criteria andWord3IsNull() {
            addCriterion("word3 is null");
            return (Criteria) this;
        }

        public Criteria andWord3IsNotNull() {
            addCriterion("word3 is not null");
            return (Criteria) this;
        }

        public Criteria andWord3EqualTo(String value) {
            addCriterion("word3 =", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3NotEqualTo(String value) {
            addCriterion("word3 <>", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3GreaterThan(String value) {
            addCriterion("word3 >", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3GreaterThanOrEqualTo(String value) {
            addCriterion("word3 >=", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3LessThan(String value) {
            addCriterion("word3 <", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3LessThanOrEqualTo(String value) {
            addCriterion("word3 <=", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3Like(String value) {
            addCriterion("word3 like", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3NotLike(String value) {
            addCriterion("word3 not like", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3In(List<String> values) {
            addCriterion("word3 in", values, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3NotIn(List<String> values) {
            addCriterion("word3 not in", values, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3Between(String value1, String value2) {
            addCriterion("word3 between", value1, value2, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3NotBetween(String value1, String value2) {
            addCriterion("word3 not between", value1, value2, "word3");
            return (Criteria) this;
        }

        public Criteria andImg3IsNull() {
            addCriterion("img3 is null");
            return (Criteria) this;
        }

        public Criteria andImg3IsNotNull() {
            addCriterion("img3 is not null");
            return (Criteria) this;
        }

        public Criteria andImg3EqualTo(String value) {
            addCriterion("img3 =", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3NotEqualTo(String value) {
            addCriterion("img3 <>", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3GreaterThan(String value) {
            addCriterion("img3 >", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3GreaterThanOrEqualTo(String value) {
            addCriterion("img3 >=", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3LessThan(String value) {
            addCriterion("img3 <", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3LessThanOrEqualTo(String value) {
            addCriterion("img3 <=", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3Like(String value) {
            addCriterion("img3 like", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3NotLike(String value) {
            addCriterion("img3 not like", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3In(List<String> values) {
            addCriterion("img3 in", values, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3NotIn(List<String> values) {
            addCriterion("img3 not in", values, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3Between(String value1, String value2) {
            addCriterion("img3 between", value1, value2, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3NotBetween(String value1, String value2) {
            addCriterion("img3 not between", value1, value2, "img3");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：card
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 
     * Criterion
     * 数据库表：card
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}