package com.zdb.demo.entity;

import java.util.ArrayList;
import java.util.List;

public class CityExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table city
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table city
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table city
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table city
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table city
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     *  构造查询条件,city
     */
    public CityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,city
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,city
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,city
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,city
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,city
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,city
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,city
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,city
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,city
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,city
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,city
     *
     * @param limitStart
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * ,city
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * ,city
     *
     * @param limitEnd
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * ,city
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * 
     * GeneratedCriteria
     * 数据库表：city
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("Name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("Name like", "%"+ value+"%", "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("Name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("Name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("City is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("City is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("City =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("City <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("City >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("City >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("City <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("City <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("City like","%"+ value+"%", "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("City not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("City in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("City not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("City between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("City not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andScenicSpotIsNull() {
            addCriterion("Scenic_Spot is null");
            return (Criteria) this;
        }

        public Criteria andScenicSpotIsNotNull() {
            addCriterion("Scenic_Spot is not null");
            return (Criteria) this;
        }

        public Criteria andScenicSpotEqualTo(String value) {
            addCriterion("Scenic_Spot =", value, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotNotEqualTo(String value) {
            addCriterion("Scenic_Spot <>", value, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotGreaterThan(String value) {
            addCriterion("Scenic_Spot >", value, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotGreaterThanOrEqualTo(String value) {
            addCriterion("Scenic_Spot >=", value, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotLessThan(String value) {
            addCriterion("Scenic_Spot <", value, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotLessThanOrEqualTo(String value) {
            addCriterion("Scenic_Spot <=", value, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotLike(String value) {
            addCriterion("Scenic_Spot like", "%"+ value+"%", "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotNotLike(String value) {
            addCriterion("Scenic_Spot not like", value, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotIn(List<String> values) {
            addCriterion("Scenic_Spot in", values, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotNotIn(List<String> values) {
            addCriterion("Scenic_Spot not in", values, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotBetween(String value1, String value2) {
            addCriterion("Scenic_Spot between", value1, value2, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andScenicSpotNotBetween(String value1, String value2) {
            addCriterion("Scenic_Spot not between", value1, value2, "scenicSpot");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Float value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Float value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Float value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Float value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Float value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Float value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Float> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Float> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Float value1, Float value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Float value1, Float value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Float value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Float value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Float value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Float value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Float value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Float value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Float> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Float> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Float value1, Float value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Float value1, Float value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andImgviewIsNull() {
            addCriterion("imgView is null");
            return (Criteria) this;
        }

        public Criteria andImgviewIsNotNull() {
            addCriterion("imgView is not null");
            return (Criteria) this;
        }

        public Criteria andImgviewEqualTo(String value) {
            addCriterion("imgView =", value, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewNotEqualTo(String value) {
            addCriterion("imgView <>", value, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewGreaterThan(String value) {
            addCriterion("imgView >", value, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewGreaterThanOrEqualTo(String value) {
            addCriterion("imgView >=", value, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewLessThan(String value) {
            addCriterion("imgView <", value, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewLessThanOrEqualTo(String value) {
            addCriterion("imgView <=", value, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewLike(String value) {
            addCriterion("imgView like", value, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewNotLike(String value) {
            addCriterion("imgView not like", value, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewIn(List<String> values) {
            addCriterion("imgView in", values, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewNotIn(List<String> values) {
            addCriterion("imgView not in", values, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewBetween(String value1, String value2) {
            addCriterion("imgView between", value1, value2, "imgview");
            return (Criteria) this;
        }

        public Criteria andImgviewNotBetween(String value1, String value2) {
            addCriterion("imgView not between", value1, value2, "imgview");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andIntroduceIsNull() {
            addCriterion("introduce is null");
            return (Criteria) this;
        }

        public Criteria andIntroduceIsNotNull() {
            addCriterion("introduce is not null");
            return (Criteria) this;
        }

        public Criteria andIntroduceEqualTo(String value) {
            addCriterion("introduce =", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotEqualTo(String value) {
            addCriterion("introduce <>", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceGreaterThan(String value) {
            addCriterion("introduce >", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceGreaterThanOrEqualTo(String value) {
            addCriterion("introduce >=", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLessThan(String value) {
            addCriterion("introduce <", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLessThanOrEqualTo(String value) {
            addCriterion("introduce <=", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceLike(String value) {
            addCriterion("introduce like", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotLike(String value) {
            addCriterion("introduce not like", value, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceIn(List<String> values) {
            addCriterion("introduce in", values, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotIn(List<String> values) {
            addCriterion("introduce not in", values, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceBetween(String value1, String value2) {
            addCriterion("introduce between", value1, value2, "introduce");
            return (Criteria) this;
        }

        public Criteria andIntroduceNotBetween(String value1, String value2) {
            addCriterion("introduce not between", value1, value2, "introduce");
            return (Criteria) this;
        }

        public Criteria andDakatimeIsNull() {
            addCriterion("dakatime is null");
            return (Criteria) this;
        }

        public Criteria andDakatimeIsNotNull() {
            addCriterion("dakatime is not null");
            return (Criteria) this;
        }

        public Criteria andDakatimeEqualTo(String value) {
            addCriterion("dakatime =", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeNotEqualTo(String value) {
            addCriterion("dakatime <>", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeGreaterThan(String value) {
            addCriterion("dakatime >", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeGreaterThanOrEqualTo(String value) {
            addCriterion("dakatime >=", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeLessThan(String value) {
            addCriterion("dakatime <", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeLessThanOrEqualTo(String value) {
            addCriterion("dakatime <=", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeLike(String value) {
            addCriterion("dakatime like", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeNotLike(String value) {
            addCriterion("dakatime not like", value, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeIn(List<String> values) {
            addCriterion("dakatime in", values, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeNotIn(List<String> values) {
            addCriterion("dakatime not in", values, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeBetween(String value1, String value2) {
            addCriterion("dakatime between", value1, value2, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakatimeNotBetween(String value1, String value2) {
            addCriterion("dakatime not between", value1, value2, "dakatime");
            return (Criteria) this;
        }

        public Criteria andDakapeopleIsNull() {
            addCriterion("dakapeople is null");
            return (Criteria) this;
        }

        public Criteria andDakapeopleIsNotNull() {
            addCriterion("dakapeople is not null");
            return (Criteria) this;
        }

        public Criteria andDakapeopleEqualTo(String value) {
            addCriterion("dakapeople =", value, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleNotEqualTo(String value) {
            addCriterion("dakapeople <>", value, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleGreaterThan(String value) {
            addCriterion("dakapeople >", value, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleGreaterThanOrEqualTo(String value) {
            addCriterion("dakapeople >=", value, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleLessThan(String value) {
            addCriterion("dakapeople <", value, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleLessThanOrEqualTo(String value) {
            addCriterion("dakapeople <=", value, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleLike(String value) {
            addCriterion("dakapeople like", value, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleNotLike(String value) {
            addCriterion("dakapeople not like", value, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleIn(List<String> values) {
            addCriterion("dakapeople in", values, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleNotIn(List<String> values) {
            addCriterion("dakapeople not in", values, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleBetween(String value1, String value2) {
            addCriterion("dakapeople between", value1, value2, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andDakapeopleNotBetween(String value1, String value2) {
            addCriterion("dakapeople not between", value1, value2, "dakapeople");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsIsNull() {
            addCriterion("famousallusions is null");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsIsNotNull() {
            addCriterion("famousallusions is not null");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsEqualTo(String value) {
            addCriterion("famousallusions =", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsNotEqualTo(String value) {
            addCriterion("famousallusions <>", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsGreaterThan(String value) {
            addCriterion("famousallusions >", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsGreaterThanOrEqualTo(String value) {
            addCriterion("famousallusions >=", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsLessThan(String value) {
            addCriterion("famousallusions <", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsLessThanOrEqualTo(String value) {
            addCriterion("famousallusions <=", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsLike(String value) {
            addCriterion("famousallusions like", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsNotLike(String value) {
            addCriterion("famousallusions not like", value, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsIn(List<String> values) {
            addCriterion("famousallusions in", values, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsNotIn(List<String> values) {
            addCriterion("famousallusions not in", values, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsBetween(String value1, String value2) {
            addCriterion("famousallusions between", value1, value2, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andFamousallusionsNotBetween(String value1, String value2) {
            addCriterion("famousallusions not between", value1, value2, "famousallusions");
            return (Criteria) this;
        }

        public Criteria andSmalltitleIsNull() {
            addCriterion("smalltitle is null");
            return (Criteria) this;
        }

        public Criteria andSmalltitleIsNotNull() {
            addCriterion("smalltitle is not null");
            return (Criteria) this;
        }

        public Criteria andSmalltitleEqualTo(String value) {
            addCriterion("smalltitle =", value, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleNotEqualTo(String value) {
            addCriterion("smalltitle <>", value, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleGreaterThan(String value) {
            addCriterion("smalltitle >", value, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleGreaterThanOrEqualTo(String value) {
            addCriterion("smalltitle >=", value, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleLessThan(String value) {
            addCriterion("smalltitle <", value, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleLessThanOrEqualTo(String value) {
            addCriterion("smalltitle <=", value, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleLike(String value) {
            addCriterion("smalltitle like", value, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleNotLike(String value) {
            addCriterion("smalltitle not like", value, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleIn(List<String> values) {
            addCriterion("smalltitle in", values, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleNotIn(List<String> values) {
            addCriterion("smalltitle not in", values, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleBetween(String value1, String value2) {
            addCriterion("smalltitle between", value1, value2, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andSmalltitleNotBetween(String value1, String value2) {
            addCriterion("smalltitle not between", value1, value2, "smalltitle");
            return (Criteria) this;
        }

        public Criteria andWord1IsNull() {
            addCriterion("word1 is null");
            return (Criteria) this;
        }

        public Criteria andWord1IsNotNull() {
            addCriterion("word1 is not null");
            return (Criteria) this;
        }

        public Criteria andWord1EqualTo(String value) {
            addCriterion("word1 =", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1NotEqualTo(String value) {
            addCriterion("word1 <>", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1GreaterThan(String value) {
            addCriterion("word1 >", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1GreaterThanOrEqualTo(String value) {
            addCriterion("word1 >=", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1LessThan(String value) {
            addCriterion("word1 <", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1LessThanOrEqualTo(String value) {
            addCriterion("word1 <=", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1Like(String value) {
            addCriterion("word1 like", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1NotLike(String value) {
            addCriterion("word1 not like", value, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1In(List<String> values) {
            addCriterion("word1 in", values, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1NotIn(List<String> values) {
            addCriterion("word1 not in", values, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1Between(String value1, String value2) {
            addCriterion("word1 between", value1, value2, "word1");
            return (Criteria) this;
        }

        public Criteria andWord1NotBetween(String value1, String value2) {
            addCriterion("word1 not between", value1, value2, "word1");
            return (Criteria) this;
        }

        public Criteria andImg1IsNull() {
            addCriterion("img1 is null");
            return (Criteria) this;
        }

        public Criteria andImg1IsNotNull() {
            addCriterion("img1 is not null");
            return (Criteria) this;
        }

        public Criteria andImg1EqualTo(String value) {
            addCriterion("img1 =", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1NotEqualTo(String value) {
            addCriterion("img1 <>", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1GreaterThan(String value) {
            addCriterion("img1 >", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1GreaterThanOrEqualTo(String value) {
            addCriterion("img1 >=", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1LessThan(String value) {
            addCriterion("img1 <", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1LessThanOrEqualTo(String value) {
            addCriterion("img1 <=", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1Like(String value) {
            addCriterion("img1 like", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1NotLike(String value) {
            addCriterion("img1 not like", value, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1In(List<String> values) {
            addCriterion("img1 in", values, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1NotIn(List<String> values) {
            addCriterion("img1 not in", values, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1Between(String value1, String value2) {
            addCriterion("img1 between", value1, value2, "img1");
            return (Criteria) this;
        }

        public Criteria andImg1NotBetween(String value1, String value2) {
            addCriterion("img1 not between", value1, value2, "img1");
            return (Criteria) this;
        }

        public Criteria andWord2IsNull() {
            addCriterion("word2 is null");
            return (Criteria) this;
        }

        public Criteria andWord2IsNotNull() {
            addCriterion("word2 is not null");
            return (Criteria) this;
        }

        public Criteria andWord2EqualTo(String value) {
            addCriterion("word2 =", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2NotEqualTo(String value) {
            addCriterion("word2 <>", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2GreaterThan(String value) {
            addCriterion("word2 >", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2GreaterThanOrEqualTo(String value) {
            addCriterion("word2 >=", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2LessThan(String value) {
            addCriterion("word2 <", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2LessThanOrEqualTo(String value) {
            addCriterion("word2 <=", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2Like(String value) {
            addCriterion("word2 like", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2NotLike(String value) {
            addCriterion("word2 not like", value, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2In(List<String> values) {
            addCriterion("word2 in", values, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2NotIn(List<String> values) {
            addCriterion("word2 not in", values, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2Between(String value1, String value2) {
            addCriterion("word2 between", value1, value2, "word2");
            return (Criteria) this;
        }

        public Criteria andWord2NotBetween(String value1, String value2) {
            addCriterion("word2 not between", value1, value2, "word2");
            return (Criteria) this;
        }

        public Criteria andImg2IsNull() {
            addCriterion("img2 is null");
            return (Criteria) this;
        }

        public Criteria andImg2IsNotNull() {
            addCriterion("img2 is not null");
            return (Criteria) this;
        }

        public Criteria andImg2EqualTo(String value) {
            addCriterion("img2 =", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2NotEqualTo(String value) {
            addCriterion("img2 <>", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2GreaterThan(String value) {
            addCriterion("img2 >", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2GreaterThanOrEqualTo(String value) {
            addCriterion("img2 >=", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2LessThan(String value) {
            addCriterion("img2 <", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2LessThanOrEqualTo(String value) {
            addCriterion("img2 <=", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2Like(String value) {
            addCriterion("img2 like", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2NotLike(String value) {
            addCriterion("img2 not like", value, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2In(List<String> values) {
            addCriterion("img2 in", values, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2NotIn(List<String> values) {
            addCriterion("img2 not in", values, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2Between(String value1, String value2) {
            addCriterion("img2 between", value1, value2, "img2");
            return (Criteria) this;
        }

        public Criteria andImg2NotBetween(String value1, String value2) {
            addCriterion("img2 not between", value1, value2, "img2");
            return (Criteria) this;
        }

        public Criteria andWord3IsNull() {
            addCriterion("word3 is null");
            return (Criteria) this;
        }

        public Criteria andWord3IsNotNull() {
            addCriterion("word3 is not null");
            return (Criteria) this;
        }

        public Criteria andWord3EqualTo(String value) {
            addCriterion("word3 =", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3NotEqualTo(String value) {
            addCriterion("word3 <>", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3GreaterThan(String value) {
            addCriterion("word3 >", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3GreaterThanOrEqualTo(String value) {
            addCriterion("word3 >=", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3LessThan(String value) {
            addCriterion("word3 <", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3LessThanOrEqualTo(String value) {
            addCriterion("word3 <=", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3Like(String value) {
            addCriterion("word3 like", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3NotLike(String value) {
            addCriterion("word3 not like", value, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3In(List<String> values) {
            addCriterion("word3 in", values, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3NotIn(List<String> values) {
            addCriterion("word3 not in", values, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3Between(String value1, String value2) {
            addCriterion("word3 between", value1, value2, "word3");
            return (Criteria) this;
        }

        public Criteria andWord3NotBetween(String value1, String value2) {
            addCriterion("word3 not between", value1, value2, "word3");
            return (Criteria) this;
        }

        public Criteria andImg3IsNull() {
            addCriterion("img3 is null");
            return (Criteria) this;
        }

        public Criteria andImg3IsNotNull() {
            addCriterion("img3 is not null");
            return (Criteria) this;
        }

        public Criteria andImg3EqualTo(String value) {
            addCriterion("img3 =", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3NotEqualTo(String value) {
            addCriterion("img3 <>", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3GreaterThan(String value) {
            addCriterion("img3 >", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3GreaterThanOrEqualTo(String value) {
            addCriterion("img3 >=", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3LessThan(String value) {
            addCriterion("img3 <", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3LessThanOrEqualTo(String value) {
            addCriterion("img3 <=", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3Like(String value) {
            addCriterion("img3 like", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3NotLike(String value) {
            addCriterion("img3 not like", value, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3In(List<String> values) {
            addCriterion("img3 in", values, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3NotIn(List<String> values) {
            addCriterion("img3 not in", values, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3Between(String value1, String value2) {
            addCriterion("img3 between", value1, value2, "img3");
            return (Criteria) this;
        }

        public Criteria andImg3NotBetween(String value1, String value2) {
            addCriterion("img3 not between", value1, value2, "img3");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：city
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 
     * Criterion
     * 数据库表：city
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}