package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 
 * City
 * 数据库表：city
 */
public class City implements Serializable {

    /**
     * 
     * 表字段 : city.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : city.Name
     */
    private String name;

    /**
     * 
     * 表字段 : city.City
     */
    private String city;

    /**
     * 
     * 表字段 : city.Scenic_Spot
     */
    private String scenicSpot;

    /**
     * 
     * 表字段 : city.longitude
     */
    private Float longitude;

    /**
     * 
     * 表字段 : city.latitude
     */
    private Float latitude;

    /**
     * 
     * 表字段 : city.imgView
     */
    private String imgview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table city
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:city.id
     *
     * @return city.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:city.id
     *
     * @param id the value for city.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:city.Name
     *
     * @return city.Name, 
     */
    public String getName() {
        return name;
    }

    /**
     * 设置  字段:city.Name
     *
     * @param name the value for city.Name, 
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取  字段:city.City
     *
     * @return city.City, 
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置  字段:city.City
     *
     * @param city the value for city.City, 
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * 获取  字段:city.Scenic_Spot
     *
     * @return city.Scenic_Spot, 
     */
    public String getScenicSpot() {
        return scenicSpot;
    }

    /**
     * 设置  字段:city.Scenic_Spot
     *
     * @param scenicSpot the value for city.Scenic_Spot, 
     */
    public void setScenicSpot(String scenicSpot) {
        this.scenicSpot = scenicSpot == null ? null : scenicSpot.trim();
    }

    /**
     * 获取  字段:city.longitude
     *
     * @return city.longitude, 
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * 设置  字段:city.longitude
     *
     * @param longitude the value for city.longitude, 
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * 获取  字段:city.latitude
     *
     * @return city.latitude, 
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * 设置  字段:city.latitude
     *
     * @param latitude the value for city.latitude, 
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * 获取  字段:city.imgView
     *
     * @return city.imgView, 
     */
    public String getImgview() {
        return imgview;
    }

    /**
     * 设置  字段:city.imgView
     *
     * @param imgview the value for city.imgView, 
     */
    public void setImgview(String imgview) {
        this.imgview = imgview == null ? null : imgview.trim();
    }
}