package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 
 * City
 * 数据库表：city
 */
public class City implements Serializable {

    /**
     * 
     * 表字段 : city.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : city.Name
     */
    private String name;

    /**
     * 
     * 表字段 : city.City
     */
    private String city;

    /**
     * 
     * 表字段 : city.Scenic_Spot
     */
    private String scenicSpot;

    /**
     * 
     * 表字段 : city.longitude
     */
    private Float longitude;

    /**
     * 
     * 表字段 : city.latitude
     */
    private Float latitude;

    /**
     * 
     * 表字段 : city.imgView
     */
    private String imgview;

    /**
     * 
     * 表字段 : city.title
     */
    private String title;

    /**
     * 
     * 表字段 : city.introduce
     */
    private String introduce;

    /**
     * 
     * 表字段 : city.dakatime
     */
    private String dakatime;

    /**
     * 
     * 表字段 : city.dakapeople
     */
    private String dakapeople;

    /**
     * 
     * 表字段 : city.famousallusions
     */
    private String famousallusions;

    /**
     * 
     * 表字段 : city.smalltitle
     */
    private String smalltitle;

    /**
     * 
     * 表字段 : city.word1
     */
    private String word1;

    /**
     * 
     * 表字段 : city.img1
     */
    private String img1;

    /**
     * 
     * 表字段 : city.word2
     */
    private String word2;

    /**
     * 
     * 表字段 : city.img2
     */
    private String img2;

    /**
     * 
     * 表字段 : city.word3
     */
    private String word3;

    /**
     * 
     * 表字段 : city.img3
     */
    private String img3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table city
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:city.id
     *
     * @return city.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:city.id
     *
     * @param id the value for city.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:city.Name
     *
     * @return city.Name, 
     */
    public String getName() {
        return name;
    }

    /**
     * 设置  字段:city.Name
     *
     * @param name the value for city.Name, 
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取  字段:city.City
     *
     * @return city.City, 
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置  字段:city.City
     *
     * @param city the value for city.City, 
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * 获取  字段:city.Scenic_Spot
     *
     * @return city.Scenic_Spot, 
     */
    public String getScenicSpot() {
        return scenicSpot;
    }

    /**
     * 设置  字段:city.Scenic_Spot
     *
     * @param scenicSpot the value for city.Scenic_Spot, 
     */
    public void setScenicSpot(String scenicSpot) {
        this.scenicSpot = scenicSpot == null ? null : scenicSpot.trim();
    }

    /**
     * 获取  字段:city.longitude
     *
     * @return city.longitude, 
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * 设置  字段:city.longitude
     *
     * @param longitude the value for city.longitude, 
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * 获取  字段:city.latitude
     *
     * @return city.latitude, 
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * 设置  字段:city.latitude
     *
     * @param latitude the value for city.latitude, 
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * 获取  字段:city.imgView
     *
     * @return city.imgView, 
     */
    public String getImgview() {
        return imgview;
    }

    /**
     * 设置  字段:city.imgView
     *
     * @param imgview the value for city.imgView, 
     */
    public void setImgview(String imgview) {
        this.imgview = imgview == null ? null : imgview.trim();
    }

    /**
     * 获取  字段:city.title
     *
     * @return city.title, 
     */
    public String getTitle() {
        return title;
    }

    /**
     * 设置  字段:city.title
     *
     * @param title the value for city.title, 
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * 获取  字段:city.introduce
     *
     * @return city.introduce, 
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * 设置  字段:city.introduce
     *
     * @param introduce the value for city.introduce, 
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * 获取  字段:city.dakatime
     *
     * @return city.dakatime, 
     */
    public String getDakatime() {
        return dakatime;
    }

    /**
     * 设置  字段:city.dakatime
     *
     * @param dakatime the value for city.dakatime, 
     */
    public void setDakatime(String dakatime) {
        this.dakatime = dakatime == null ? null : dakatime.trim();
    }

    /**
     * 获取  字段:city.dakapeople
     *
     * @return city.dakapeople, 
     */
    public String getDakapeople() {
        return dakapeople;
    }

    /**
     * 设置  字段:city.dakapeople
     *
     * @param dakapeople the value for city.dakapeople, 
     */
    public void setDakapeople(String dakapeople) {
        this.dakapeople = dakapeople == null ? null : dakapeople.trim();
    }

    /**
     * 获取  字段:city.famousallusions
     *
     * @return city.famousallusions, 
     */
    public String getFamousallusions() {
        return famousallusions;
    }

    /**
     * 设置  字段:city.famousallusions
     *
     * @param famousallusions the value for city.famousallusions, 
     */
    public void setFamousallusions(String famousallusions) {
        this.famousallusions = famousallusions == null ? null : famousallusions.trim();
    }

    /**
     * 获取  字段:city.smalltitle
     *
     * @return city.smalltitle, 
     */
    public String getSmalltitle() {
        return smalltitle;
    }

    /**
     * 设置  字段:city.smalltitle
     *
     * @param smalltitle the value for city.smalltitle, 
     */
    public void setSmalltitle(String smalltitle) {
        this.smalltitle = smalltitle == null ? null : smalltitle.trim();
    }

    /**
     * 获取  字段:city.word1
     *
     * @return city.word1, 
     */
    public String getWord1() {
        return word1;
    }

    /**
     * 设置  字段:city.word1
     *
     * @param word1 the value for city.word1, 
     */
    public void setWord1(String word1) {
        this.word1 = word1 == null ? null : word1.trim();
    }

    /**
     * 获取  字段:city.img1
     *
     * @return city.img1, 
     */
    public String getImg1() {
        return img1;
    }

    /**
     * 设置  字段:city.img1
     *
     * @param img1 the value for city.img1, 
     */
    public void setImg1(String img1) {
        this.img1 = img1 == null ? null : img1.trim();
    }

    /**
     * 获取  字段:city.word2
     *
     * @return city.word2, 
     */
    public String getWord2() {
        return word2;
    }

    /**
     * 设置  字段:city.word2
     *
     * @param word2 the value for city.word2, 
     */
    public void setWord2(String word2) {
        this.word2 = word2 == null ? null : word2.trim();
    }

    /**
     * 获取  字段:city.img2
     *
     * @return city.img2, 
     */
    public String getImg2() {
        return img2;
    }

    /**
     * 设置  字段:city.img2
     *
     * @param img2 the value for city.img2, 
     */
    public void setImg2(String img2) {
        this.img2 = img2 == null ? null : img2.trim();
    }

    /**
     * 获取  字段:city.word3
     *
     * @return city.word3, 
     */
    public String getWord3() {
        return word3;
    }

    /**
     * 设置  字段:city.word3
     *
     * @param word3 the value for city.word3, 
     */
    public void setWord3(String word3) {
        this.word3 = word3 == null ? null : word3.trim();
    }

    /**
     * 获取  字段:city.img3
     *
     * @return city.img3, 
     */
    public String getImg3() {
        return img3;
    }

    /**
     * 设置  字段:city.img3
     *
     * @param img3 the value for city.img3, 
     */
    public void setImg3(String img3) {
        this.img3 = img3 == null ? null : img3.trim();
    }
}