package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 
 * Clock
 * 数据库表：clock
 */
public class Clock implements Serializable {

    /**
     * 
     * 表字段 : clock.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : clock.user_id
     */
    private Integer userId;

    /**
     * 
     * 表字段 : clock.city_id
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clock
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:clock.id
     *
     * @return clock.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:clock.id
     *
     * @param id the value for clock.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:clock.user_id
     *
     * @return clock.user_id, 
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置  字段:clock.user_id
     *
     * @param userId the value for clock.user_id, 
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取  字段:clock.city_id
     *
     * @return clock.city_id, 
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * 设置  字段:clock.city_id
     *
     * @param cityId the value for clock.city_id, 
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
}