package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 
 * Collection
 * 数据库表：collection
 */
public class Collection implements Serializable {

    /**
     * 
     * 表字段 : collection.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : collection.user_id
     */
    private Integer userId;

    /**
     * 
     * 表字段 : collection.answer_id
     */
    private Integer answerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table collection
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:collection.id
     *
     * @return collection.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:collection.id
     *
     * @param id the value for collection.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:collection.user_id
     *
     * @return collection.user_id, 
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置  字段:collection.user_id
     *
     * @param userId the value for collection.user_id, 
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取  字段:collection.answer_id
     *
     * @return collection.answer_id, 
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * 设置  字段:collection.answer_id
     *
     * @param answerId the value for collection.answer_id, 
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }
}