package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 
 * CreateRoute
 * 数据库表：create_route
 */
public class CreateRoute implements Serializable {

    /**
     * 
     * 表字段 : create_route.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : create_route.choose_city
     */
    private String chooseCity;

    /**
     * 
     * 表字段 : create_route.route_name
     */
    private String routeName;

    /**
     * 
     * 表字段 : create_route.expected_duration
     */
    private String expectedDuration;

    /**
     * 
     * 表字段 : create_route.remarks
     */
    private String remarks;

    /**
     * 
     * 表字段 : create_route.user_id
     */
    private Integer userId;

    /**
     * 
     * 表字段 : create_route.add_cityid
     */
    private String addCityid;

    /**
     * 
     * 表字段 : create_route.backgroundUrl
     */
    private String backgroundurl;

    //用户名
    private String userName;

    //城市名
    private String cityName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table create_route
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:create_route.id
     *
     * @return create_route.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:create_route.id
     *
     * @param id the value for create_route.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:create_route.choose_city
     *
     * @return create_route.choose_city, 
     */
    public String getChooseCity() {
        return chooseCity;
    }

    /**
     * 设置  字段:create_route.choose_city
     *
     * @param chooseCity the value for create_route.choose_city, 
     */
    public void setChooseCity(String chooseCity) {
        this.chooseCity = chooseCity == null ? null : chooseCity.trim();
    }

    /**
     * 获取  字段:create_route.route_name
     *
     * @return create_route.route_name, 
     */
    public String getRouteName() {
        return routeName;
    }

    /**
     * 设置  字段:create_route.route_name
     *
     * @param routeName the value for create_route.route_name, 
     */
    public void setRouteName(String routeName) {
        this.routeName = routeName == null ? null : routeName.trim();
    }

    /**
     * 获取  字段:create_route.expected_duration
     *
     * @return create_route.expected_duration, 
     */
    public String getExpectedDuration() {
        return expectedDuration;
    }

    /**
     * 设置  字段:create_route.expected_duration
     *
     * @param expectedDuration the value for create_route.expected_duration, 
     */
    public void setExpectedDuration(String expectedDuration) {
        this.expectedDuration = expectedDuration == null ? null : expectedDuration.trim();
    }

    /**
     * 获取  字段:create_route.remarks
     *
     * @return create_route.remarks, 
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * 设置  字段:create_route.remarks
     *
     * @param remarks the value for create_route.remarks, 
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * 获取  字段:create_route.user_id
     *
     * @return create_route.user_id, 
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置  字段:create_route.user_id
     *
     * @param userId the value for create_route.user_id, 
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取  字段:create_route.add_cityid
     *
     * @return create_route.add_cityid, 
     */
    public String getAddCityid() {
        return addCityid;
    }

    /**
     * 设置  字段:create_route.add_cityid
     *
     * @param addCityid the value for create_route.add_cityid, 
     */
    public void setAddCityid(String addCityid) {
        this.addCityid = addCityid == null ? null : addCityid.trim();
    }

    /**
     * 获取  字段:create_route.backgroundUrl
     *
     * @return create_route.backgroundUrl, 
     */
    public String getBackgroundurl() {
        return backgroundurl;
    }

    /**
     * 设置  字段:create_route.backgroundUrl
     *
     * @param backgroundurl the value for create_route.backgroundUrl, 
     */
    public void setBackgroundurl(String backgroundurl) {
        this.backgroundurl = backgroundurl == null ? null : backgroundurl.trim();
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
}