package com.zdb.demo.entity;

import java.util.ArrayList;
import java.util.List;

public class CreateRouteExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table create_route
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table create_route
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table create_route
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table create_route
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table create_route
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     *  构造查询条件,create_route
     */
    public CreateRouteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,create_route
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,create_route
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,create_route
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,create_route
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,create_route
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,create_route
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,create_route
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,create_route
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,create_route
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,create_route
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,create_route
     *
     * @param limitStart
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * ,create_route
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * ,create_route
     *
     * @param limitEnd
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * ,create_route
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * 
     * GeneratedCriteria
     * 数据库表：create_route
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChooseCityIsNull() {
            addCriterion("choose_city is null");
            return (Criteria) this;
        }

        public Criteria andChooseCityIsNotNull() {
            addCriterion("choose_city is not null");
            return (Criteria) this;
        }

        public Criteria andChooseCityEqualTo(String value) {
            addCriterion("choose_city =", value, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityNotEqualTo(String value) {
            addCriterion("choose_city <>", value, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityGreaterThan(String value) {
            addCriterion("choose_city >", value, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityGreaterThanOrEqualTo(String value) {
            addCriterion("choose_city >=", value, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityLessThan(String value) {
            addCriterion("choose_city <", value, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityLessThanOrEqualTo(String value) {
            addCriterion("choose_city <=", value, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityLike(String value) {
            addCriterion("choose_city like", value, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityNotLike(String value) {
            addCriterion("choose_city not like","%"+ value+"%", "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityIn(List<String> values) {
            addCriterion("choose_city in", values, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityNotIn(List<String> values) {
            addCriterion("choose_city not in", values, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityBetween(String value1, String value2) {
            addCriterion("choose_city between", value1, value2, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andChooseCityNotBetween(String value1, String value2) {
            addCriterion("choose_city not between", value1, value2, "chooseCity");
            return (Criteria) this;
        }

        public Criteria andRouteNameIsNull() {
            addCriterion("route_name is null");
            return (Criteria) this;
        }

        public Criteria andRouteNameIsNotNull() {
            addCriterion("route_name is not null");
            return (Criteria) this;
        }

        public Criteria andRouteNameEqualTo(String value) {
            addCriterion("route_name =", value, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameNotEqualTo(String value) {
            addCriterion("route_name <>", value, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameGreaterThan(String value) {
            addCriterion("route_name >", value, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameGreaterThanOrEqualTo(String value) {
            addCriterion("route_name >=", value, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameLessThan(String value) {
            addCriterion("route_name <", value, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameLessThanOrEqualTo(String value) {
            addCriterion("route_name <=", value, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameLike(String value) {
            addCriterion("route_name like", value, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameNotLike(String value) {
            addCriterion("route_name not like", value, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameIn(List<String> values) {
            addCriterion("route_name in", values, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameNotIn(List<String> values) {
            addCriterion("route_name not in", values, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameBetween(String value1, String value2) {
            addCriterion("route_name between", value1, value2, "routeName");
            return (Criteria) this;
        }

        public Criteria andRouteNameNotBetween(String value1, String value2) {
            addCriterion("route_name not between", value1, value2, "routeName");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationIsNull() {
            addCriterion("expected_duration is null");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationIsNotNull() {
            addCriterion("expected_duration is not null");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationEqualTo(String value) {
            addCriterion("expected_duration =", value, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationNotEqualTo(String value) {
            addCriterion("expected_duration <>", value, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationGreaterThan(String value) {
            addCriterion("expected_duration >", value, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationGreaterThanOrEqualTo(String value) {
            addCriterion("expected_duration >=", value, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationLessThan(String value) {
            addCriterion("expected_duration <", value, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationLessThanOrEqualTo(String value) {
            addCriterion("expected_duration <=", value, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationLike(String value) {
            addCriterion("expected_duration like", value, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationNotLike(String value) {
            addCriterion("expected_duration not like", value, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationIn(List<String> values) {
            addCriterion("expected_duration in", values, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationNotIn(List<String> values) {
            addCriterion("expected_duration not in", values, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationBetween(String value1, String value2) {
            addCriterion("expected_duration between", value1, value2, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andExpectedDurationNotBetween(String value1, String value2) {
            addCriterion("expected_duration not between", value1, value2, "expectedDuration");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAddCityidIsNull() {
            addCriterion("add_cityid is null");
            return (Criteria) this;
        }

        public Criteria andAddCityidIsNotNull() {
            addCriterion("add_cityid is not null");
            return (Criteria) this;
        }

        public Criteria andAddCityidEqualTo(String value) {
            addCriterion("add_cityid =", value, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidNotEqualTo(String value) {
            addCriterion("add_cityid <>", value, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidGreaterThan(String value) {
            addCriterion("add_cityid >", value, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidGreaterThanOrEqualTo(String value) {
            addCriterion("add_cityid >=", value, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidLessThan(String value) {
            addCriterion("add_cityid <", value, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidLessThanOrEqualTo(String value) {
            addCriterion("add_cityid <=", value, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidLike(String value) {
            addCriterion("add_cityid like", value, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidNotLike(String value) {
            addCriterion("add_cityid not like", value, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidIn(List<String> values) {
            addCriterion("add_cityid in", values, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidNotIn(List<String> values) {
            addCriterion("add_cityid not in", values, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidBetween(String value1, String value2) {
            addCriterion("add_cityid between", value1, value2, "addCityid");
            return (Criteria) this;
        }

        public Criteria andAddCityidNotBetween(String value1, String value2) {
            addCriterion("add_cityid not between", value1, value2, "addCityid");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlIsNull() {
            addCriterion("backgroundUrl is null");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlIsNotNull() {
            addCriterion("backgroundUrl is not null");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlEqualTo(String value) {
            addCriterion("backgroundUrl =", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlNotEqualTo(String value) {
            addCriterion("backgroundUrl <>", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlGreaterThan(String value) {
            addCriterion("backgroundUrl >", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlGreaterThanOrEqualTo(String value) {
            addCriterion("backgroundUrl >=", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlLessThan(String value) {
            addCriterion("backgroundUrl <", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlLessThanOrEqualTo(String value) {
            addCriterion("backgroundUrl <=", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlLike(String value) {
            addCriterion("backgroundUrl like", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlNotLike(String value) {
            addCriterion("backgroundUrl not like", value, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlIn(List<String> values) {
            addCriterion("backgroundUrl in", values, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlNotIn(List<String> values) {
            addCriterion("backgroundUrl not in", values, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlBetween(String value1, String value2) {
            addCriterion("backgroundUrl between", value1, value2, "backgroundurl");
            return (Criteria) this;
        }

        public Criteria andBackgroundurlNotBetween(String value1, String value2) {
            addCriterion("backgroundUrl not between", value1, value2, "backgroundurl");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：create_route
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 
     * Criterion
     * 数据库表：create_route
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}