package com.zdb.demo.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * Dianzan
 * 数据库表：dianzan
 */
public class Dianzan implements Serializable {

    /**
     * 
     * 表字段 : dianzan.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : dianzan.answer_id
     */
    private Integer answerId;

    /**
     * 
     * 表字段 : dianzan.dianzan_user
     */
    private Integer dianzanUser;

    /**
     * 
     * 表字段 : dianzan.createTime
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dianzan
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:dianzan.id
     *
     * @return dianzan.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:dianzan.id
     *
     * @param id the value for dianzan.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:dianzan.answer_id
     *
     * @return dianzan.answer_id, 
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * 设置  字段:dianzan.answer_id
     *
     * @param answerId the value for dianzan.answer_id, 
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * 获取  字段:dianzan.dianzan_user
     *
     * @return dianzan.dianzan_user, 
     */
    public Integer getDianzanUser() {
        return dianzanUser;
    }

    /**
     * 设置  字段:dianzan.dianzan_user
     *
     * @param dianzanUser the value for dianzan.dianzan_user, 
     */
    public void setDianzanUser(Integer dianzanUser) {
        this.dianzanUser = dianzanUser;
    }

    /**
     * 获取  字段:dianzan.createTime
     *
     * @return dianzan.createTime, 
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 设置  字段:dianzan.createTime
     *
     * @param createtime the value for dianzan.createTime, 
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}