package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 
 * Follow
 * 数据库表：follow
 */
public class Follow implements Serializable {

    /**
     * 
     * 表字段 : follow.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : follow.user_id
     */
    private Integer userId;

    /**
     * 
     * 表字段 : follow.followed_user
     */
    private Integer followedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table follow
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:follow.id
     *
     * @return follow.id, 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置  字段:follow.id
     *
     * @param id the value for follow.id, 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:follow.user_id
     *
     * @return follow.user_id, 
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置  字段:follow.user_id
     *
     * @param userId the value for follow.user_id, 
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取  字段:follow.followed_user
     *
     * @return follow.followed_user, 
     */
    public Integer getFollowedUser() {
        return followedUser;
    }

    /**
     * 设置  字段:follow.followed_user
     *
     * @param followedUser the value for follow.followed_user, 
     */
    public void setFollowedUser(Integer followedUser) {
        this.followedUser = followedUser;
    }
}