package com.zdb.demo.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 * Reply
 * 数据库表：reply
 */
public class Reply implements Serializable {

    /**
     * 
     * 表字段 : reply.lr_id
     */
    private Integer lrId;

    /**
     * 
     * 表字段 : reply.lr_name
     */
    private String lrName;

    /**
     * 
     * 表字段 : reply.lr_date
     */
    private Date lrDate;

    /**
     * 
     * 表字段 : reply.lr_content
     */
    private String lrContent;

    /**
     * 
     * 表字段 : reply.lr_for_word
     */
    private String lrForWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reply
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:reply.lr_id
     *
     * @return reply.lr_id, 
     */
    public Integer getLrId() {
        return lrId;
    }

    /**
     * 设置  字段:reply.lr_id
     *
     * @param lrId the value for reply.lr_id, 
     */
    public void setLrId(Integer lrId) {
        this.lrId = lrId;
    }

    /**
     * 获取  字段:reply.lr_name
     *
     * @return reply.lr_name, 
     */
    public String getLrName() {
        return lrName;
    }

    /**
     * 设置  字段:reply.lr_name
     *
     * @param lrName the value for reply.lr_name, 
     */
    public void setLrName(String lrName) {
        this.lrName = lrName == null ? null : lrName.trim();
    }

    /**
     * 获取  字段:reply.lr_date
     *
     * @return reply.lr_date, 
     */
    public Date getLrDate() {
        return lrDate;
    }

    /**
     * 设置  字段:reply.lr_date
     *
     * @param lrDate the value for reply.lr_date, 
     */
    public void setLrDate(Date lrDate) {
        this.lrDate = lrDate;
    }

    /**
     * 获取  字段:reply.lr_content
     *
     * @return reply.lr_content, 
     */
    public String getLrContent() {
        return lrContent;
    }

    /**
     * 设置  字段:reply.lr_content
     *
     * @param lrContent the value for reply.lr_content, 
     */
    public void setLrContent(String lrContent) {
        this.lrContent = lrContent == null ? null : lrContent.trim();
    }

    /**
     * 获取  字段:reply.lr_for_word
     *
     * @return reply.lr_for_word, 
     */
    public String getLrForWord() {
        return lrForWord;
    }

    /**
     * 设置  字段:reply.lr_for_word
     *
     * @param lrForWord the value for reply.lr_for_word, 
     */
    public void setLrForWord(String lrForWord) {
        this.lrForWord = lrForWord == null ? null : lrForWord.trim();
    }
}