package com.zdb.demo.entity;

import java.io.Serializable;

/**
 * 
 * Sign
 * 数据库表：sign
 */
public class Sign implements Serializable {

    /**
     * 
     * 表字段 : sign.sign_id
     */
    private Integer signId;

    /**
     * 
     * 表字段 : sign.user_id
     */
    private Integer userId;

    /**
     * 
     * 表字段 : sign.continue_da
     */
    private Integer continueDa;

    /**
     * 
     * 表字段 : sign.rignin_time
     */
    private Integer rigninTime;

    /**
     * 
     * 表字段 : sign.rignin_coun
     */
    private Integer rigninCoun;

    /**
     * 
     * 表字段 : sign.sign_get_po
     */
    private String signGetPo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sign
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取  字段:sign.sign_id
     *
     * @return sign.sign_id, 
     */
    public Integer getSignId() {
        return signId;
    }

    /**
     * 设置  字段:sign.sign_id
     *
     * @param signId the value for sign.sign_id, 
     */
    public void setSignId(Integer signId) {
        this.signId = signId;
    }

    /**
     * 获取  字段:sign.user_id
     *
     * @return sign.user_id, 
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置  字段:sign.user_id
     *
     * @param userId the value for sign.user_id, 
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取  字段:sign.continue_da
     *
     * @return sign.continue_da, 
     */
    public Integer getContinueDa() {
        return continueDa;
    }

    /**
     * 设置  字段:sign.continue_da
     *
     * @param continueDa the value for sign.continue_da, 
     */
    public void setContinueDa(Integer continueDa) {
        this.continueDa = continueDa;
    }

    /**
     * 获取  字段:sign.rignin_time
     *
     * @return sign.rignin_time, 
     */
    public Integer getRigninTime() {
        return rigninTime;
    }

    /**
     * 设置  字段:sign.rignin_time
     *
     * @param rigninTime the value for sign.rignin_time, 
     */
    public void setRigninTime(Integer rigninTime) {
        this.rigninTime = rigninTime;
    }

    /**
     * 获取  字段:sign.rignin_coun
     *
     * @return sign.rignin_coun, 
     */
    public Integer getRigninCoun() {
        return rigninCoun;
    }

    /**
     * 设置  字段:sign.rignin_coun
     *
     * @param rigninCoun the value for sign.rignin_coun, 
     */
    public void setRigninCoun(Integer rigninCoun) {
        this.rigninCoun = rigninCoun;
    }

    /**
     * 获取  字段:sign.sign_get_po
     *
     * @return sign.sign_get_po, 
     */
    public String getSignGetPo() {
        return signGetPo;
    }

    /**
     * 设置  字段:sign.sign_get_po
     *
     * @param signGetPo the value for sign.sign_get_po, 
     */
    public void setSignGetPo(String signGetPo) {
        this.signGetPo = signGetPo == null ? null : signGetPo.trim();
    }
}