package com.zdb.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TravelsExample {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table travels
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table travels
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table travels
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table travels
     *
     * @mbggenerated
     */
    protected Integer limitStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table travels
     *
     * @mbggenerated
     */
    protected Integer limitEnd;

    /**
     *  构造查询条件,travels
     */
    public TravelsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,travels
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,travels
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,travels
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,travels
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,travels
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,travels
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,travels
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,travels
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,travels
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,travels
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * ,travels
     *
     * @param limitStart
     */
    public void setLimitStart(Integer limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * ,travels
     */
    public Integer getLimitStart() {
        return limitStart;
    }

    /**
     * ,travels
     *
     * @param limitEnd
     */
    public void setLimitEnd(Integer limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * ,travels
     */
    public Integer getLimitEnd() {
        return limitEnd;
    }

    /**
     * 
     * GeneratedCriteria
     * 数据库表：travels
     */
    protected abstract static class GeneratedCriteria {

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAnswerIdIsNull() {
            addCriterion("answer_id is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNotNull() {
            addCriterion("answer_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdEqualTo(Integer value) {
            addCriterion("answer_id =", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotEqualTo(Integer value) {
            addCriterion("answer_id <>", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThan(Integer value) {
            addCriterion("answer_id >", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("answer_id >=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThan(Integer value) {
            addCriterion("answer_id <", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThanOrEqualTo(Integer value) {
            addCriterion("answer_id <=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIn(List<Integer> values) {
            addCriterion("answer_id in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotIn(List<Integer> values) {
            addCriterion("answer_id not in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdBetween(Integer value1, Integer value2) {
            addCriterion("answer_id between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("answer_id not between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andWordsIsNull() {
            addCriterion("words is null");
            return (Criteria) this;
        }

        public Criteria andWordsIsNotNull() {
            addCriterion("words is not null");
            return (Criteria) this;
        }

        public Criteria andWordsEqualTo(String value) {
            addCriterion("words =", value, "words");
            return (Criteria) this;
        }

        public Criteria andWordsNotEqualTo(String value) {
            addCriterion("words <>", value, "words");
            return (Criteria) this;
        }

        public Criteria andWordsGreaterThan(String value) {
            addCriterion("words >", value, "words");
            return (Criteria) this;
        }

        public Criteria andWordsGreaterThanOrEqualTo(String value) {
            addCriterion("words >=", value, "words");
            return (Criteria) this;
        }

        public Criteria andWordsLessThan(String value) {
            addCriterion("words <", value, "words");
            return (Criteria) this;
        }

        public Criteria andWordsLessThanOrEqualTo(String value) {
            addCriterion("words <=", value, "words");
            return (Criteria) this;
        }

        public Criteria andWordsLike(String value) {
            addCriterion("words like", value, "words");
            return (Criteria) this;
        }

        public Criteria andWordsNotLike(String value) {
            addCriterion("words not like", value, "words");
            return (Criteria) this;
        }

        public Criteria andWordsIn(List<String> values) {
            addCriterion("words in", values, "words");
            return (Criteria) this;
        }

        public Criteria andWordsNotIn(List<String> values) {
            addCriterion("words not in", values, "words");
            return (Criteria) this;
        }

        public Criteria andWordsBetween(String value1, String value2) {
            addCriterion("words between", value1, value2, "words");
            return (Criteria) this;
        }

        public Criteria andWordsNotBetween(String value1, String value2) {
            addCriterion("words not between", value1, value2, "words");
            return (Criteria) this;
        }

        public Criteria andShowuserimgIsNull() {
            addCriterion("showUserImg is null");
            return (Criteria) this;
        }

        public Criteria andShowuserimgIsNotNull() {
            addCriterion("showUserImg is not null");
            return (Criteria) this;
        }

        public Criteria andShowuserimgEqualTo(String value) {
            addCriterion("showUserImg =", value, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgNotEqualTo(String value) {
            addCriterion("showUserImg <>", value, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgGreaterThan(String value) {
            addCriterion("showUserImg >", value, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgGreaterThanOrEqualTo(String value) {
            addCriterion("showUserImg >=", value, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgLessThan(String value) {
            addCriterion("showUserImg <", value, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgLessThanOrEqualTo(String value) {
            addCriterion("showUserImg <=", value, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgLike(String value) {
            addCriterion("showUserImg like", value, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgNotLike(String value) {
            addCriterion("showUserImg not like", value, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgIn(List<String> values) {
            addCriterion("showUserImg in", values, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgNotIn(List<String> values) {
            addCriterion("showUserImg not in", values, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgBetween(String value1, String value2) {
            addCriterion("showUserImg between", value1, value2, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andShowuserimgNotBetween(String value1, String value2) {
            addCriterion("showUserImg not between", value1, value2, "showuserimg");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("location like", "%"+value+"%", "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andPraseCountIsNull() {
            addCriterion("prase_count is null");
            return (Criteria) this;
        }

        public Criteria andPraseCountIsNotNull() {
            addCriterion("prase_count is not null");
            return (Criteria) this;
        }

        public Criteria andPraseCountEqualTo(Integer value) {
            addCriterion("prase_count =", value, "praseCount");
            return (Criteria) this;
        }

        public Criteria andPraseCountNotEqualTo(Integer value) {
            addCriterion("prase_count <>", value, "praseCount");
            return (Criteria) this;
        }

        public Criteria andPraseCountGreaterThan(Integer value) {
            addCriterion("prase_count >", value, "praseCount");
            return (Criteria) this;
        }

        public Criteria andPraseCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("prase_count >=", value, "praseCount");
            return (Criteria) this;
        }

        public Criteria andPraseCountLessThan(Integer value) {
            addCriterion("prase_count <", value, "praseCount");
            return (Criteria) this;
        }

        public Criteria andPraseCountLessThanOrEqualTo(Integer value) {
            addCriterion("prase_count <=", value, "praseCount");
            return (Criteria) this;
        }

        public Criteria andPraseCountIn(List<Integer> values) {
            addCriterion("prase_count in", values, "praseCount");
            return (Criteria) this;
        }

        public Criteria andPraseCountNotIn(List<Integer> values) {
            addCriterion("prase_count not in", values, "praseCount");
            return (Criteria) this;
        }

        public Criteria andPraseCountBetween(Integer value1, Integer value2) {
            addCriterion("prase_count between", value1, value2, "praseCount");
            return (Criteria) this;
        }

        public Criteria andPraseCountNotBetween(Integer value1, Integer value2) {
            addCriterion("prase_count not between", value1, value2, "praseCount");
            return (Criteria) this;
        }

        public Criteria andAtnameIsNull() {
            addCriterion("atName is null");
            return (Criteria) this;
        }

        public Criteria andAtnameIsNotNull() {
            addCriterion("atName is not null");
            return (Criteria) this;
        }

        public Criteria andAtnameEqualTo(String value) {
            addCriterion("atName =", value, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameNotEqualTo(String value) {
            addCriterion("atName <>", value, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameGreaterThan(String value) {
            addCriterion("atName >", value, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameGreaterThanOrEqualTo(String value) {
            addCriterion("atName >=", value, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameLessThan(String value) {
            addCriterion("atName <", value, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameLessThanOrEqualTo(String value) {
            addCriterion("atName <=", value, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameLike(String value) {
            addCriterion("atName like", value, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameNotLike(String value) {
            addCriterion("atName not like", value, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameIn(List<String> values) {
            addCriterion("atName in", values, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameNotIn(List<String> values) {
            addCriterion("atName not in", values, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameBetween(String value1, String value2) {
            addCriterion("atName between", value1, value2, "atname");
            return (Criteria) this;
        }

        public Criteria andAtnameNotBetween(String value1, String value2) {
            addCriterion("atName not between", value1, value2, "atname");
            return (Criteria) this;
        }

        public Criteria andTopicwordsIsNull() {
            addCriterion("topicWords is null");
            return (Criteria) this;
        }

        public Criteria andTopicwordsIsNotNull() {
            addCriterion("topicWords is not null");
            return (Criteria) this;
        }

        public Criteria andTopicwordsEqualTo(String value) {
            addCriterion("topicWords =", value, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsNotEqualTo(String value) {
            addCriterion("topicWords <>", value, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsGreaterThan(String value) {
            addCriterion("topicWords >", value, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsGreaterThanOrEqualTo(String value) {
            addCriterion("topicWords >=", value, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsLessThan(String value) {
            addCriterion("topicWords <", value, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsLessThanOrEqualTo(String value) {
            addCriterion("topicWords <=", value, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsLike(String value) {
            addCriterion("topicWords like", value, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsNotLike(String value) {
            addCriterion("topicWords not like", value, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsIn(List<String> values) {
            addCriterion("topicWords in", values, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsNotIn(List<String> values) {
            addCriterion("topicWords not in", values, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsBetween(String value1, String value2) {
            addCriterion("topicWords between", value1, value2, "topicwords");
            return (Criteria) this;
        }

        public Criteria andTopicwordsNotBetween(String value1, String value2) {
            addCriterion("topicWords not between", value1, value2, "topicwords");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：travels
     */
    public static class Criteria extends GeneratedCriteria {


        protected Criteria() {
            super();
        }
    }

    /**
     * 
     * Criterion
     * 数据库表：travels
     */
    public static class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}